# Generated by Django 3.2.9 on 2021-11-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cartimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartImages',
            new_name='CartImage',
        ),
    ]
