# Generated by Django 3.2.9 on 2021-11-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cartimages_cartimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartimage',
            name='product_img',
            field=models.ImageField(height_field='200', upload_to='images', width_field='200'),
        ),
    ]
