# Generated by Django 3.2.9 on 2021-11-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cartimage_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartimage',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cartimage',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cartimage',
            name='product_img',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='images', verbose_name='Profile Picture'),
        ),
    ]
