# Generated by Django 3.2.9 on 2021-11-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211113_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartimage',
            name='product_img',
        ),
        migrations.AddField(
            model_name='cartimage',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', help_text='Profile Picture', null=True, upload_to='images', verbose_name='Profile Picture', width_field='image_width'),
        ),
    ]
